### ISSUE TITLE
Incorrect I2C reference used in FS300::readData.

### ISSUE THREAD

**Issue by brandonbeattie22** [sparkfun/SparkFun_FS3000_Arduino_Library#4]
### Subject of the issue

EDIT: Looks like somebody already made a pull request for this a while ago but it hasn't been accepted:
https://github.com/sparkfun/SparkFun_FS3000_Arduino_Library/pull/3

In `FS300::begin()` there as a parameter for a `TwoWire` that is defaulted in the .h file to the standard `Wire` and is stored as `FS300::_i2cPort`. In the function `readData`, instead of using `_i2cPort`, that code uses `Wire`, regardless of whether `_i2cPort` is `Wire` or somebody else, like `Wire2` in my case.

Right now it is:
```
void FS3000::readData(uint8_t* buffer_in) {
    // Wire.reqeustFrom contains the beginTransmission and endTransmission in it. 
	Wire.requestFrom(FS3000_DEVICE_ADDRESS, 5);  // Request 5 Bytes

  uint8_t i = 0;
	while(Wire.available())
	{
		buffer_in[i] = Wire.read();				// Receive Byte
    i += 1;
	}
  //Serial.print("i:");
  //Serial.println(i);
}
```

But so that `readData` works with any `TwoWire` given by client code to `.begin()`, I think this would be a good change:
```
void FS3000::readData(uint8_t* buffer_in) {
    // _i2cPort->reqeustFrom contains the beginTransmission and endTransmission in it. 
	_i2cPort->requestFrom(FS3000_DEVICE_ADDRESS, 5);  // Request 5 Bytes

  uint8_t i = 0;
	while(_i2cPort->available())
	{
		buffer_in[i] = _i2cPort->read();				// Receive Byte
    i += 1;
	}
  //Serial.print("i:");
  //Serial.println(i);
}
```

### Your workbench
* What development board or microcontroller are you using?
Teensy4.1
* What version of hardware or breakout board are you using? 
FS3000-1005 breakout from SparkFun.
* How is the breakout board wired to your microcontroller?
I2C, on the third I2C for the Teensy4.1, `Wire2` in ArduinoIDE.
* How is everything being powered?
USB to MacBook
* Are there any additional details that may help us help you?

### Steps to reproduce
I've edited the given example sketch to use `Wire2`. The functions other than `readData` that access I2C use the `_i2cPort` member so `fs.begin(Wire2)` does not fail, causing the code to get to the `loop` function and just read all 0's.

I imagine you could use any non-`Wire` I2C for any board and it should behave the same.
```
#include <Wire.h>
#include <SparkFun_FS3000_Arduino_Library.h> //Click here to get the library: http://librarymanager/All#SparkFun_FS3000

FS3000 fs;

void setup()
{
  Serial.begin(115200);
  Serial.println("Example 1 - Reading values from the FS3000");

  Wire2.begin();

  if (fs.begin(Wire2) == false) //Begin communication over I2C
  {
    Serial.println("The sensor did not respond. Please check wiring.");
    while(1); //Freeze
  }

  // Set the range to match which version of the sensor you are using.
  // FS3000-1005 (0-7.23 m/sec) --->>>  AIRFLOW_RANGE_7_MPS
  // FS3000-1015 (0-15 m/sec)   --->>>  AIRFLOW_RANGE_15_MPS
  fs.setRange(AIRFLOW_RANGE_7_MPS);
//  fs.setRange(AIRFLOW_RANGE_15_MPS); 

  Serial.println("Sensor is connected properly.");
}

void loop()
{
    Serial.print("FS3000 Readings \tRaw: ");
    Serial.print(fs.readRaw()); // note, this returns an int from 0-3686
    
    Serial.print("\tm/s: ");
    Serial.print(fs.readMetersPerSecond()); // note, this returns a float from 0-7.23 for the FS3000-1005, and 0-15 for the FS3000-1015 
    
    Serial.print("\tmph: ");
    Serial.println(fs.readMilesPerHour()); // note, this returns a float from 0-16.17 for the FS3000-1005, and 0-33.55 for the FS3000-1015 
    
    
    delay(1000); // note, reponse time on the sensor is 125ms
}
```

### Expected behavior
The sketch uses the user-given `TwoWire` for communication with the board at all times.

Output:
```
Example 1 - Reading values from the FS3000
Sensor is connected properly.
FS3000 Readings 	Raw: 440	m/s: 0.07	mph: 
FS3000 Readings 	Raw: 438	m/s: 0.06	mph: 0.14
```

### Actual behavior
The sketch uses the user-given `TwoWire` for communication during setup, but when reading data, uses the hardcoded `Wire`, which only works if the user gives `Wire` as their I2C line.

Output:
```
Example 1 - Reading values from the FS3000
Sensor is connected properly.
FS3000 Readings 	Raw: 0	m/s: 0.00	mph: 
FS3000 Readings 	Raw: 0	m/s: 0.00	mph: 0.00
```

**Comment by lewispg228** [comment]
Thank you for bringing this to our attention. What you have shown here all makes sense. I'm grabbing some hardware to verify on my end. Should be able to get this fixed/pulled-in soon.

**Comment by lewispg228** [comment]
Verified with a [SparkFun IoT Redboard - ESP32](https://www.sparkfun.com/products/19177). Used Example01_BasicReadings, but modified to use Wire1 on 33/32:

![image](https://github.com/sparkfun/SparkFun_FS3000_Arduino_Library/assets/601236/bdbfc89e-d6fa-4935-9df1-848b7b67e00e)

Merged in [pull request 3](https://github.com/sparkfun/SparkFun_FS3000_Arduino_Library/pull/3) and just created a new release. Should be good to go.

Thanks again!
-Pete
